version: 3
endpoint: https://igztcrvfwwpfgriueiwb.hasura.ap-south-1.nhost.run
metadata_directory: metadata
migrations_directory: migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
